service_incident_rules:
  - service_name: frontend
    incident_rule:
      condition_match_type: match-all

      conditions:
        - field: message
          operation: matches
          expected_value: ".*stage.*"
        - field: tags
          operation: contains
          expected_value: "severity:info"

      incident_properties:
        message: This is a test message
        priority: P3

        stakeholder_properties:
          message: Message for stakeholders
          enable: true
